### PR TITLE
fix: make the search case-insensitive

### LINKED ISSUE #14: bug: Case-sensitive search
I tried the search queries and found that the search is case-sensitive. I think it might be bad for an uneducated user.
**Code:** https://github.com/lonnieezell/forum-example/blob/17b9cb0f63e5bff786fd6dd7a3106ac50511457c/app/Controllers/HelpController.php#L41
**File:** /help/1_user-account/removing-account.md
**Text:** General instructions for deleting an account.
**Search tests:**
 Removing, emoving, account, Account -> ok
removing, REMOVING, AccounT-> fail

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR makes the `search` functionality case-insensitive.

Fixes #14

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by neznaika0** [comment]
Fast fix :smile: 
I added `mb_strtolower()`, but now the first character doesn't work when searching: REMOVING -> fail, EMOVING -> ok. 

Everything is fine with the other file "Registering Account" (ReGiSte -> ok). Is there some kind of cache in the system?

**Comment by neznaika0** [comment]
It seems the search uses the content inside, not the filename. But then why does it find "emoving"? There is no word "removing" inside. Wonders

**Comment by michalsn** [comment]
Can you paste here the entire content of the file (as code), plus the filename? I will check it out later.

**Comment by neznaika0** [comment]
It from forum **lonnieezell**. https://github.com/lonnieezell/forum-example/tree/develop/help

**Comment by michalsn** [comment]
It should work now.

**Review by neznaika0 — APPROVED** [review]
Fine! I don't see where this is implemented, but the content search seems to be working: GENeral -> ok

File: src/Pages/File.php [hunk 1]
```diff
@@ -131,13 +131,14 @@ public function parse(bool $parseMarkdown = true): Content
...
     {
+        $query      = mb_strtolower($query);
         $rawContent = mb_strtolower((string) $this->load(true));
 
         $document = $this->parser->parse($rawContent, false);
         $content  = new Content($document->getContent(), $document->getYAML() ?? []);
 
         $score = 0;
-        $score += mb_substr_count($this->getName(), $query);
+        $score += mb_substr_count(mb_strtolower($this->getName()), $query);
```
Comment (michalsn) [inline src/Pages/File.php:141]: Here, we check the file name.

**Comment by michalsn** [comment]
Thanks for the feedback!
